image: registry.git.avidi.tech/docker/teracy/angular-cli:latest

stages:
    - install
    - build
    - deploy

.libs-cache:
    tags:
        - docker
    cache:
        paths:
            - node_modules/

.develop:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" && $CI_COMMIT_TAG == null

install:
    stage: install
    extends:
        - .libs-cache
        - .develop
    script:
        - npm i

build-web-ssr:
    stage: build
    tags:
        - docker
    extends:
        .develop
    cache:
        paths:
            - dist/
            - node_modules/
    artifacts:
        expire_in: 1 day
        paths:
            - dist/
    script:
        - npm install --save-dev @angular-devkit/build-angular
        - npm run build:static

deploy-latest:
    stage: deploy
    services:
        - registry.gitlab.com/docker.hub/docker:dind
    image: registry.gitlab.com/docker.hub/docker:latest
    extends:
        .develop
    cache:
        paths:
            - dist/
    script:
        - CONTAINER_IMAGE="$CI_REGISTRY/$CI_PROJECT_PATH"
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build --tag $CONTAINER_IMAGE:latest .
        - docker push $CONTAINER_IMAGE:latest
        - docker logout
    tags:
        - docker


deploy-stage:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" && $CI_COMMIT_TAG != null
  script:
    - echo only on tags
    - echo $CI_COMMIT_TAG
    - env

