FROM node:16 as build
WORKDIR /usr/src/app
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
RUN npm install -g @angular/cli
COPY . .
RUN npm run build --prod
CMD ["ng", "serve", "--host", "0.0.0.0"]