// Temporary
import { IInstrument } from 'trading';

export const defaultInstruments = [
  {
    contractSize: 20,
    description: 'E-Mini Nasdaq-100',
    exchange: 'CME',
    productCode: 'NQ',
    id: 'NQH2.CME',
    precision: 2,
    symbol: 'NQH2',
    tickSize: 0.25,
  },
  {
    contractSize: 50,
    description: 'E-Mini S&P 500',
    exchange: 'CME',
    productCode: 'ES',
    id: 'ESH2.CME',
    precision: 2,
    symbol: 'ESH2',
    tickSize: 0.25,
  },
  {
    contractSize: 5,
    description: 'Mini-sized Dow Futures ($5)',
    exchange: 'CBOT',
    productCode: 'YM',
    id: 'YMH2.CBOT',
    precision: 0,
    symbol: 'YMH2',
    tickSize: 1,
  },
  {
    contractSize: 50,
    description: 'E-mini Russell 2000 Index Futures',
    exchange: 'CME',
    id: 'RTYH2.CME',
    productCode: 'RTY',
    precision: 1,
    symbol: 'RTYH2',
    tickSize: 0.1,
  },
  {
    contractSize: 125000,
    description: 'Euro Fx',
    exchange: 'CME',
    id: '6EH2.CME',
    productCode: '6E',
    precision: 5,
    symbol: '6EH2',
    tickSize: 0.00005,
  },
  {
    contractSize: 1000,
    description: '30 Year US Treasury Bond Futures',
    exchange: 'CBOT',
    id: 'ZBH2.CBOT',
    symbol: 'ZBH2',
    productCode: 'ZB',
    fraction: 32,
    tickSize: 0.03125,
    precision: 5
  },
  {
    contractSize: 1000,
    description: '10 Year US Treasury Note Futures',
    exchange: 'CBOT',
    id: 'ZNH2.CBOT',
    productCode: 'ZN',
    symbol: 'ZNH2',
    fraction: 32,
    tickSize: 0.015625,
    precision: 6,
  }
] as IInstrument[];
