// Temporary
export const defaultInstruments = [
  {
    contractSize: 20,
    description: 'E-Mini Nasdaq-100',
    exchange: 'CME',
    productCode: 'NQ',
    id: 'NQU1.CME',
    precision: 2,
    symbol: 'NQU1',
    tickSize: 0.25,
  },
  {
    contractSize: 50,
    description: 'E-Mini S&P 500',
    exchange: 'CME',
    productCode: 'ES',
    id: 'ESU1.CME',
    precision: 2,
    symbol: 'ESU1',
    tickSize: 0.25,
  },
  {
    contractSize: 5,
    description: 'Mini-sized Dow Futures ($5)',
    exchange: 'CBOT',
    productCode: 'YM',
    id: 'YMU1.CBOT',
    precision: 0,
    symbol: 'YMU1',
    tickSize: 1,
  },
  {
    contractSize: 50,
    description: 'E-mini Russell 2000 Index Futures',
    exchange: 'CME',
    id: 'RTYU1.CME',
    productCode: 'RTY',
    precision: 1,
    symbol: 'RTYU1',
    tickSize: 0.1,
  },
  {
    contractSize: 125000,
    description: 'Euro Fx',
    exchange: 'CME',
    id: '6EU1.CME',
    productCode: '6E',
    precision: 5,
    symbol: '6EU1',
    tickSize: 0.00005,
  },
  {
    contractSize: 1000,
    description: '30 Year US Treasury Bond Futures',
    exchange: 'CBOT',
    id: 'ZBU1.CBOT',
    symbol: 'ZBU1',
    productCode: 'ZB',
    tickSize: 0.03125,
    precision: 5
  },
  {
    contractSize: 1000,
    description: '10 Year US Treasury Note Futures',
    exchange: 'CBOT',
    id: 'ZNU1.CBOT',
    productCode: 'ZN',
    symbol: 'ZNU1',
    tickSize: 0.015625,
    precision: 6
  }
];
