export enum RealtimeType {
  Order = 'Order',
  Position = 'Position',
  Bar = 'Bar',
  Quote = 'Quote',
  TradePrint = 'TradePrint',
  Level2 = 'Level2',
  VolumePrint = 'VolumePrint',
  Connect = 'Connect',
  Message = 'Message',
  Error = 'Error',
  Settle = 'SettlementPrice',
  Delay = 'Delay',
  Activity = 'Activity',
}
